### ISSUE TITLE
CTF Estimation

### ISSUE THREAD

**Issue by DennisDannecker** [czimaginginstitute/MotionCor3#12]
Hello,

I have a question regarding the ability of MotionCor3 to estimate the CTF?
How exactly does one call the CTF estimate function in MotionCor3.
From looking at the list of command line parameters/options to be entered I could not find any parameter indicating CTF estimation.
Is CTF estimated by default, which parameters are dedicated to control CTF estimation.
Furthermore, is there a separate dedicated documentation/manual for MotionCor3 or does the official manual for MotionCor2 serves as the manaual, the parameters should be the same, right?

Thank you for providing this powerful tool to the field.

Edit: 
So CTF appears to be estimated by default. Are there any parameters that allow one control over the CTF estimate, defocus range, patch, astigmatism...
Which CTF estimate algorithm is employed by MotionCor3, one of the better known ctffind4, GCTF, or something different? 

Best
Dennis

**Comment by apeck12** [comment]
Hi Dennis,

MotionCor3 implements its own algorithm for CTF estimation rather than calling an external package. The only adjustable parameter for CTF estimation is `-ExtPhase`, which controls whether an extra phase shift is estimated. Shawn recently released another open-source software package, GCtfFind, specifically for CTF estimation which can be found here: https://github.com/czimaginginstitute/GCtfFind. For both MotionCor3 and GCtfFind, the optimal defocus and astigmatism search ranges are estimated automatically. Patch-wise defocus estimation will be implemented soon.

We look forward to receiving feedback from the community and hope you’ll reach out with any other questions.

Ariana
